services:
  postgres:
    image: postgres:16-alpine
    container_name: clouddns-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clouddns
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d clouddns" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./internal/adapters/repository/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    image: redis:7-alpine
    container_name: clouddns-cache
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  clouddns:
    build: .
    container_name: clouddns-server
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/clouddns?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - DNS_ADDR=:53
      - API_ADDR=:8080
      - NODE_ID=docker-node
    ports:
      - "10053:53/udp"
      - "10053:53/tcp"
      - "8080:8080"
      - "853:853"
    restart: unless-stopped
